// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpzun_vM0cr3lhLVTRL1_Zeg3y--fDGrI',
    appId: '1:906979460302:web:07e060edee779bb0a4fc9f',
    messagingSenderId: '906979460302',
    projectId: 'dalel-ca09b',
    authDomain: 'dalel-ca09b.firebaseapp.com',
    storageBucket: 'dalel-ca09b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKPeQlXTITEGqe0XabOaZNukhS7Bym7aQ',
    appId: '1:906979460302:android:f79badafccf119b3a4fc9f',
    messagingSenderId: '906979460302',
    projectId: 'dalel-ca09b',
    storageBucket: 'dalel-ca09b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkKPVok0lNAiAmM9BG2Slocuww7zTEGfs',
    appId: '1:906979460302:ios:6ffdbd90fbafa5f0a4fc9f',
    messagingSenderId: '906979460302',
    projectId: 'dalel-ca09b',
    storageBucket: 'dalel-ca09b.appspot.com',
    androidClientId: '906979460302-ipgr2r28lejju22cs8befdrbkl0a7f1n.apps.googleusercontent.com',
    iosClientId: '906979460302-719icjg21o6ij1u7onkm6ncaugigg41m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ateleSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkKPVok0lNAiAmM9BG2Slocuww7zTEGfs',
    appId: '1:906979460302:ios:6ffdbd90fbafa5f0a4fc9f',
    messagingSenderId: '906979460302',
    projectId: 'dalel-ca09b',
    storageBucket: 'dalel-ca09b.appspot.com',
    androidClientId: '906979460302-ipgr2r28lejju22cs8befdrbkl0a7f1n.apps.googleusercontent.com',
    iosClientId: '906979460302-719icjg21o6ij1u7onkm6ncaugigg41m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ateleSeller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNOFA0mBMuyghMrszASydrs8_q3dodiOs',
    appId: '1:906979460302:web:d3e4d1fc9706515da4fc9f',
    messagingSenderId: '906979460302',
    projectId: 'dalel-ca09b',
    authDomain: 'dalel-ca09b.firebaseapp.com',
    storageBucket: 'dalel-ca09b.appspot.com',
  );
}
